schema_version: 1

context:
  name: zppy-interfaces
  version: "0.2.1"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/E3SM-Project/zppy-interfaces/archive/v${{ version }}.tar.gz
  sha256: 3c71dca088133da4c49e30bdd565de8ba393cee2b9742e6aea1c049b5c34d77d

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  # Build from https://github.com/E3SM-Project/zppy-interfaces/blob/v{{ version }}/conda/dev.yml
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=60
  run:
    - python >=${{ python_min }},<3.15
    - beautifulsoup4
    - lxml
    - matplotlib-base >=3.8.2
    - mpas_tools >=0.21.0
    - netcdf4
    - numpy >=2.0,<3.0
    - output_viewer ==1.3.3
    - pcmdi_metrics >=3.9.3
    - xarray >=2023.02.0
    - xcdat >=0.7.3,<1.0

tests:
  - python:
      imports:
        - zppy_interfaces
      pip_check: true
      python_version: 
        - ${{ python_min }}
        - "*"
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - zi-global-time-series --help

about:
  summary: Interfaces between external tools and zppy, E3SM post-processing toolchain
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/E3SM-Project/zppy-interfaces

extra:
  recipe-maintainers:
    - andrewdnolan
    - mahf708
    - xylar
    - tomvothecoder
    - forsyth2
    - chengzhuzhang
